name: CI Pipeline for API & UI Tests
on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:
    inputs:
      browser:
        description: "Choose browser for UI tests"
        required: true
        default: "firefox"
        type: choice
        options:
          - chrome
          - firefox
          - edge
jobs:
 api-tests:
      name: Build and run API tests
      runs-on: ubuntu-latest
      
      steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore Dependencies
        run: dotnet restore
        
      - name: Build 
        run: dotnet build --no-restore 
        
      - name: Run API Tests
        run: dotnet test --no-build --filter Category=API --logger trx --results-directory TestResults

      - name: Upload API test results
        uses: actions/upload-artifact@v4
        with:
          name: api-test-results
          path: TestResults
 ui-tests:
    name: Build and run UI tests
    runs-on: ubuntu-latest
    needs: api-tests
    if: always()
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install ChromeDriver
        if: ${{ github.event.inputs.browser == 'chrome' }}
        uses: browser-actions/setup-chrome@v1

      - name: Install Firefox
        if: ${{ github.event.inputs.browser == 'firefox' }}
        uses: browser-actions/setup-firefox@v1

      - name: Install EdgeDriver
        if: ${{ github.event.inputs.browser == 'edge' }}
        uses: browser-actions/setup-edge@v1

      - name: Restore Dependencies
        run: dotnet restore
        working-directory: ./Tests

      - name: Build 
        run: dotnet build --no-restore 
        working-directory: ./Tests

      - name: Ensure Download Directory Exists
        run: mkdir -p ./Tests/Downloads

      # Step 5: Set correct permissions
      - name: Set correct permissions
        run: |
          chmod -R 755 ./Tests/screenshot
          chmod -R 755 ./Tests/downloads
          chmod -R 755 ./Tests/bin
          chmod -R 755 ./Tests/obj

      - name: Run UI Tests
        run: dotnet test --no-build --filter Category=UI --logger trx --results-directory TestResults
        env:
          BROWSER: ${{ github.event.inputs.browser }}
        working-directory: ./Tests

      - name: Upload UI Test Results
        uses: actions/upload-artifact@v4
        with:
          name: ui-test-results
          path: TestResults

      - name: Upload UI Test Screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: ui-test-screenshots
          path: ./Tests/screenshot
