name: CI Pipeline for API & UI Tests
on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:
    inputs:
      browser:
        description: "Choose browser for UI tests"
        required: true
        default: "firefox"
        type: choice
        options:
          - chrome
          - firefox
          - edge
jobs:
 api-tests:
      name: Build and run API tests
      runs-on: ubuntu-latest
      
      steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore Dependencies
        run: dotnet restore
        
      - name: Build 
        run: dotnet build --no-restore 
        
      - name: Run API Tests
        run: dotnet test --no-build --filter Category=API --logger trx --results-directory TestResults

      - name: Upload API test results
        uses: actions/upload-artifact@v4
        with:
          name: api-test-results
          path: TestResults
 ui-tests:
    name: Build and run UI tests
    runs-on: ubuntu-latest
    needs: api-tests
    if: always()
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install ChromeDriver
        if: ${{ github.event.inputs.browser == 'chrome' }}
        uses: browser-actions/setup-chrome@v1

      - name: Run Chrome with custom preferences
        run: |
          google-chrome --headless --disable-gpu --no-sandbox --disable-dev-shm-usage \
          --download-default-directory=/tmp/chrome-downloads \
          --disable-popup-blocking \
          --disable-extensions \
          --disable-background-networking \
          --disable-background-timer-throttling \
          --disable-backgrounding-occluded-windows \
          --disable-breakpad \
          --disable-client-side-phishing-detection \
          --disable-component-update \
          --disable-default-apps \
          --disable-domain-reliability \
          --disable-features=AudioServiceOutOfProcess \
          --disable-hang-monitor \
          --disable-ipc-flooding-protection \
          --disable-renderer-backgrounding \
          --disable-sync \
          --force-color-profile=srgb \
          --metrics-recording-only \
          --no-first-run \
          --safebrowsing-disable-auto-update \
          --password-store=basic \
          --use-mock-keychain &
          sleep 10 # Wait for Chrome to start

      - name: Install Firefox
        if: ${{ github.event.inputs.browser == 'firefox' }}
        uses: browser-actions/setup-firefox@v1
        
      - name: Set Firefox download directory
        run: |
          run: mkdir -p $GITHUB_WORKSPACE/Downloads
          echo 'user_pref("browser.download.dir", "/tmp/firefox-downloads");' >> /tmp/firefox-prefs.js
          echo 'user_pref("browser.download.folderList", 2);' >> /tmp/firefox-prefs.js
          echo 'user_pref("browser.download.manager.showWhenStarting", false);' >> /tmp/firefox-prefs.js
          echo 'user_pref("browser.helperApps.neverAsk.saveToDisk", "application/octet-stream");' >> /tmp/firefox-prefs.js

      - name: Install EdgeDriver
        if: ${{ github.event.inputs.browser == 'edge' }}
        uses: browser-actions/setup-edge@v1

      - name: Run Edge with custom preferences
        run: |
         microsoft-edge --headless --disable-gpu --no-sandbox --disable-dev-shm-usage \
          --download-default-directory=/tmp/edge-downloads \
          --disable-popup-blocking \
          --disable-extensions \
          --disable-background-networking \
          --disable-background-timer-throttling \
          --disable-backgrounding-occluded-windows \
          --disable-breakpad \
          --disable-client-side-phishing-detection \
          --disable-component-update \
          --disable-default-apps \
          --disable-domain-reliability \
          --disable-features=AudioServiceOutOfProcess \
          --disable-hang-monitor \
          --disable-ipc-flooding-protection \
          --disable-renderer-backgrounding \
          --disable-sync \
          --force-color-profile=srgb \
          --metrics-recording-only \
          --no-first-run \
          --safebrowsing-disable-auto-update \
          --password-store=basic \
          --use-mock-keychain &
          sleep 10 # Wait for Edge to start

      - name: Restore Dependencies
        run: dotnet restore
        working-directory: ./Tests

      - name: Build 
        run: dotnet build --no-restore 
        working-directory: ./Tests

      # Step 5: Set correct permissions
      - name: Set correct permissions
        run: |
          chmod -R 755 ./Tests/bin
          chmod -R 755 ./Tests/obj

      - name: Run UI Tests
        run: dotnet test --no-build --filter Category=UI --logger trx --results-directory TestResults
        env:
          BROWSER: ${{ github.event.inputs.browser }}
        working-directory: ./Tests

      - name: Upload UI Test Results
        uses: actions/upload-artifact@v4
        with:
          name: ui-test-results
          path: TestResults

      - name: Upload UI Test Screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: ui-test-screenshots
          path: Screenshots
