name: CI Pipeline with UI Tests

on:
  pull_request:
    branches:
      - main
      
  workflow_dispatch:
    inputs:
      browser:
        description: "Choose browser for UI tests"
        required: true
        default: "firefox"
        type: choice
        options:
          - chrome
          - firefox
          - edge
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
          
      # Step 3: Set up Chrome Driver
      - name: Install Chrome and ChromeDriver
      - uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 120
          install-chromedriver: true

      # Step 4: Build the project
      - name: Build the project
        run: dotnet build --configuration Release
        working-directory: ./Tests

      # Step 5: Set correct permissions
      - name: Set correct permissions
        run: |
          chmod -R 755 ./Tests/bin
          chmod -R 755 ./Tests/obj

      # Step 6: Run UI Tests
      - name: Run UI Tests
        run: dotnet test --no-build --filter Category=UI --logger trx --results-directory TestResults
        env:
          BROWSER: ${{ github.event.inputs.browser }}
        working-directory: ./Tests

      # Step 7: Upload Test Results
      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ./Tests/TestResults
